name: Depoly to Alibaba OSS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: Setup OSS
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-hongkong.aliyuncs.com
          access-key-id: ${{ secrets.ACCESS_KEY_ID }} 
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }} 

      - name: Copy files to OSS
        run: ossutil cp -rf public oss://cattom-start/ 
